### ISSUE TITLE
It Works only in Localhost

### ISSUE THREAD

**Issue by Lazarus132** [nivianh/toc#5]
This plugin does not seem to run on the current version, whenever I want to go to the settings, a 500 error appears

Class "Plugin\ToC\Forms\Settings\ToCSettingForm" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"Plugin\\ToC\\Forms\\Settings\\ToCSettingForm\" not found at /mnt/web611/b1/05/532599505/htdocs/platform/plugins/toc/src/Http/Controllers/ToCController.php:31)

Please fix this.

**Comment by nivianh** [comment]
> This plugin does not seem to run on the current version, whenever I want to go to the settings, a 500 error appears
> 
> Class "Plugin\ToC\Forms\Settings\ToCSettingForm" not found {"userId":1,"exception":"[object] (Error(code: 0): Class "Plugin\ToC\Forms\Settings\ToCSettingForm" not found at /mnt/web611/b1/05/532599505/htdocs/platform/plugins/toc/src/Http/Controllers/ToCController.php:31)
> 
> Please fix this.

@Lazarus132 Please update to the latest version I just released

**Comment by Lazarus132** [comment]
Thanks

**Comment by Lazarus132** [comment]
Normally a table of contents should be created automatically for all h tags selected in the settings, but unfortunately I cannot see a table of contents, although I have activated it.

**Comment by Lazarus132** [comment]
Ah I see, it probably only works in the blog, would it perhaps also be possible to use that somehow for every page?

**Comment by nivianh** [comment]
> Ah I see, it probably only works in the blog, would it perhaps also be possible to use that somehow for every page?

@Lazarus132 open file /platform/plugins/toc/config/general.php and add `'Botble\Page\Models\Page',` in `supported`

`
....
'supported' => [
    'Botble\Blog\Models\Post',
    'Botble\Page\Models\Page',
],
...
`

**Comment by Lazarus132** [comment]
Thanks
