### ISSUE TITLE
How to Programmatically Add TOC to a Page and Widget Areas in Botble

### ISSUE THREAD

**Issue by Fledardev** [nivianh/toc#6]
Hello,

I'm currently working with the Easy Table of Contents plugin and need some guidance on how to achieve the following tasks via code:

Programmatically Add TOC to a Specific Page: I'd like to know the best way to insert a Table of Contents (TOC) into a specific page programmatically. Could you provide an example or point me in the right direction on how to accomplish this within the plugin's framework?

Add TOC to Widget Areas in Botble: I'm using Botble as the CMS platform and would like to add the TOC element into the widget areas provided by Botble. Is there a recommended approach or any documentation on integrating the TOC within these widget zones?

Any code snippets, documentation links, or general advice would be greatly appreciated.

Thank you for your assistance!

Best regards,

**Comment by nivianh** [comment]
@Fledardev 
add to Page can ref: https://github.com/nivianh/toc/issues/5#issuecomment-1907344480

**Comment by hubfld** [comment]
Hello @nivianh,

Thank you for your response. However, my need is not to add the TOC to a specific page, but rather to **integrate it as a widget in different sections of my site**, specifically in the sidebar of a blog post.

Could you provide any guidance or documentation on how to insert the TOC into widget areas within Botble CMS? This would allow me to display it dynamically in specific sections of the site.

Thank you for your help!

Best regards,
<img width="1440" alt="Screenshot 2024-09-06 at 07 47 08" src="https://github.com/user-attachments/assets/c6147408-adea-4632-affc-0629f9767513">

**Comment by hubfld** [comment]
Hello @nivianh, 

Could you please explain how to create a shortcode for calling the plugin on any page or post? I would like to insert the plugin content wherever I need on the site using a shortcode. 

Thank you!

**Comment by nivianh** [comment]
> Hello @nivianh,
> 
> Could you please explain how to create a shortcode for calling the plugin on any page or post? I would like to insert the plugin content wherever I need on the site using a shortcode.
> 
> Thank you!

@Fledardev 

The plugin currently does not have this feature.

**Comment by hubfld** [comment]
Hello @nivianh,

It's too bad that this feature isn't available, as it would be a very useful addition and probably easy for you to develop. In the meantime, I'll try to look into the code to manually move the display of the <div class="toc-container table-of-content contracted"> into the blog's sidebar.

Thank you!

<img width="1440" alt="Screenshot 2024-09-07 at 07 58 50" src="https://github.com/user-attachments/assets/4df6c61b-f09b-4148-aeb5-5d02c0ee5b60">

**Comment by nivianh** [comment]
> Hello @nivianh,
> 
> It's too bad that this feature isn't available, as it would be a very useful addition and probably easy for you to develop. In the meantime, I'll try to look into the code to manually move the display of the
> 
> into the blog's sidebar.
> Thank you!
> 
> <img alt="Screenshot 2024-09-07 at 07 58 50" width="1440" src="https://private-user-images.githubusercontent.com/166992104/365346393-4df6c61b-f09b-4148-aeb5-5d02c0ee5b60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODkxMDQsIm5iZiI6MTcyNTY4ODgwNCwicGF0aCI6Ii8xNjY5OTIxMDQvMzY1MzQ2MzkzLTRkZjZjNjFiLWYwOWItNDE0OC1hZWI1LTVkMDJjMGVlNWI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwNjAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzA3YzYyZTAyNzZjNWFhMjQyZDAzNDM0NWY2YzdjZWJlOGI2ZjkxMmI0ZWUyZmE1OGYyYjgxNDk4ODRmYWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uYwEgbzyE6ZwAAME15VIAEAdGGCCkV7OcRauiuDF2Hs">

@Fledardev 
It's a cool feature, but I don't have time to develop it right now
You can use javascript to move to the sidebar selection

**Comment by hubfld** [comment]
> @Fledardev It's a cool feature, but I don't have time to develop it right now You can use javascript to move to the sidebar selection

@nivianh, this is the JS custom code that I use. It is not perfect but it works : 

> // Select the parent element where the divs should appear
> var observerTarget = document.body;
> // Create a mutation observer
> var observer = new MutationObserver(function(mutations) {
>     mutations.forEach(function(mutation) {
>         // Select divs with the class 'toc-container table-of-content contracted'
>         var sourceDivs = document.querySelectorAll('.toc-container.table-of-content.contracted');
>         var destinationDiv = document.querySelector('.custom-toc'); // Replace with the actual destination class
>         if (sourceDivs.length > 0 && destinationDiv) {
>             // For each found source div, move its content to the destination div
>             sourceDivs.forEach(function(sourceDiv) {
>                 while (sourceDiv.firstChild) {
>                     destinationDiv.appendChild(sourceDiv.firstChild);
>                 }
>                 // Remove the source div once it's empty
>                 sourceDiv.remove();
>             });
>             // Stop the observer once the divs are found and processed
>             observer.disconnect();
>         }
>     });
> });
> // Set the observer options
> var config = { childList: true, subtree: true };
> // Start observing changes in the DOM
> observer.observe(observerTarget, config);
