### ISSUE TITLE
Issue with <!--ToC--> Not Rendering in Content

### ISSUE THREAD

**Issue by Fledardev** [nivianh/toc#8]
Hi @nivianh,

I've encountered an issue when **trying to manually insert the Table of Contents (ToC) using the  tag in the content of my page**. Despite inserting the  tag at the desired location, the ToC does not appear at that position, and there is no ToC displayed in the content.

`$this->theTag = '<!--ToC-->';`
`$customToCPosition = strpos($content, $this->theTag);`

**Steps to Reproduce:**
1. Insert  in the body of a page or article.
2. Save and view the page.
3. Notice that the ToC does not render where the tag was placed.

**Expected Behavior:** The Table of Contents should appear at the exact position of the  tag in the page content.

**Actual Behavior:** The ToC does not render at all when using the  tag.

Could you please investigate this issue and provide a fix? It seems the plugin is not recognizing the manual insertion tag.
Idea : how to activate $customToCPosition ?

Thanks!

**Comment by nivianh** [comment]
@Fledardev 

use `<div><!--ToC--></div>`

**Comment by hubfld** [comment]
> @Fledardev
> 
> use `<div><!--ToC--></div>`

Not working, respect only the position defined in the settings

**Comment by nivianh** [comment]
> > @Fledardev
> > use `<div><!--ToC--></div>`
> 
> Not working, respect only the position defined in the settings

@Fledardev 
can record video or take screenshot?

**Comment by hubfld** [comment]
> > > @Fledardev
> > > use `<div><!--ToC--></div>`
> > 
> > 
> > Not working, respect only the position defined in the settings
> 
> @Fledardev can record video or take screenshot?

@nivianh, this is the link : https://we.tl/t-IWHvL4jUgN

**Comment by nivianh** [comment]
@Fledardev 
No!
add to Content editor in post/page

<img width="1124" alt="Screenshot 2024-09-11 at 13 38 35" src="https://github.com/user-attachments/assets/83813a4a-2714-4a1a-966a-854a21476f58">

**Comment by hubfld** [comment]
It works, thank you. But not ideal because not possible to use `<div><!--ToC--></div>` in widget area.
